name: ESLint

on:
  push:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install ESLint and Config
        run: |
          npm install eslint-plugin-jsx-a11y@latest --save-dev
          npx install-peerdeps --dev eslint-config-airbnb
          npm install react
        
      - name: Run ESLint
        run: npx eslint .
