name: ESLint

on:
  push:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install ESLint and Config
        run: npm install eslint@7.32.0 eslint-config-airbnb@18.2.1 --save-dev

      - name: Run ESLint
        run: npx eslint .
